### ISSUE TITLE
Detecting two videos or twice a video results in crash

### ISSUE THREAD

**Issue by ariaaan** [ariaaan/traffic-signs-detector#1]
When you try to detect a video more than once, or more than two videos, the software freezes.
Problem must be in the `Detector` class.

**Comment by ariaaan** [comment]
When running this piece of code to test if the `Detector` class is the one with the problem, it works, so the problem must be in the handling of the threads in the `app,py` file.

```python
from detector.detector import create_detector_from_file

detector = create_detector_from_file('cfg/config.json')

video_path = '/home/arian/output.mp4'

detector.detect_video_feed(video_path, show_output=True)

print('VIDEO 1 - DONE!')

import time

print('VIDEO 2 STARTING IN..!')
for i in range(5):
    time.sleep(1)
    print(5 - i)

detector.detect_video_feed(video_path, show_output=True)
```

**Comment by aalzooke** [comment]
I already installed the the files , but i can't run your code and test it. 
Can you please explain how to run your program. 
Thank you
