### ISSUE TITLE
Invalid configuration file error

### ISSUE THREAD

**Issue by alevikpes** [ariaaan/traffic-signs-detector#17]
Hello!

I am trying to run an `example_video.py` and getting `detector.exceptions.FormatNotSupportedException: The configuration file does not seems to be valid` error.

Here is the full Traceback:
```python
Traceback (most recent call last):
  File "/.../traffic-signs-detector/detector/detector.py", line 267, in create_detector_from_file
    classifier_cfg['skip_classes'])
  File "/.../traffic-signs-detector/detector/classifier.py", line 13, in __init__
    self.__classifier_model = keras.models.model_from_json(model_json)
  File "/.../venvs/traffic-signs-detector/lib/python3.6/site-packages/keras/models.py", line 346, in model_from_json
    return layer_module.deserialize(config, custom_objects=custom_objects)
  File "/.../venvs/traffic-signs-detector/lib/python3.6/site-packages/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "/.../venvs/traffic-signs-detector/lib/python3.6/site-packages/keras/utils/generic_utils.py", line 140, in deserialize_keras_object
    list(custom_objects.items())))
  File "/.../venvs/traffic-signs-detector/lib/python3.6/site-packages/keras/models.py", line 1318, in from_config
    if 'class_name' not in config[0] or config[0]['class_name'] == 'Merge':
KeyError: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "example_video.py", line 3, in <module>
    detector = create_detector_from_file('./cfg/config.json')
  File "/.../traffic-signs-detector/detector/detector.py", line 280, in create_detector_from_file
    raise FormatNotSupportedException('The configuration file does not seems to be valid')
detector.exceptions.FormatNotSupportedException: The configuration file does not seems to be valid
```

If I understand the Traceback correctly, Keras expects a model file in json format, but the `Classifier` has it in the `cfg` format. My `config.cfg` (after the `make config` step) has the `model` reference to the `trafficsigns.cfg` file. Is this my problem? Where do I get the correct format?

**Comment by aiddddd** [comment]
Hi @alevikpes , im suggest you to open each of the issues and try to replace each file that has been provided because it seems like there's something wrong with certain file. All the best!

**Comment by alevikpes** [comment]
I used the `trafficsigns.cfg` provided by you on google docs. Is that one wrong, @aiddddd ?

**Comment by alevikpes** [comment]
what format should have the `model_path` file on [this line](https://github.com/ariaaan/traffic-signs-detector/blob/master/detector/classifier.py#L10)?

**Comment by alevikpes** [comment]
according to [documentation](https://www.tensorflow.org/api_docs/python/tf/keras/models/model_from_json) this must be a **json** file, but in the config model is referred to a **cfg** file. Where can I get the model json file?

**Comment by aiddddd** [comment]
> according to [documentation](https://www.tensorflow.org/api_docs/python/tf/keras/models/model_from_json) this must be a **json** file, but in the config model is referred to a **cfg** file. Where can I get the model json file?

Hi, did you already found the file? I am not really sure which json file that you meant, the first config json file is in the cfg folder while the trafficsigns json is in the data/classifier folder, you can refer 'issue about labels' and try to download data.zip if there is missing.

Goodluck! :)

**Comment by alevikpes** [comment]
> 
> 
> > according to [documentation](https://www.tensorflow.org/api_docs/python/tf/keras/models/model_from_json) this must be a **json** file, but in the config model is referred to a **cfg** file. Where can I get the model json file?
> 
> Hi, did you already found the file? I am not really sure which json file that you meant, the first config json file is in the cfg folder while the trafficsigns json is in the data/classifier folder, you can refer 'issue about labels' and try to download data.zip if there is missing.
> 
> Goodluck! :)

yes, I got it working. thank you

**Comment by Seneca-Sys** [comment]
> > > according to [documentation](https://www.tensorflow.org/api_docs/python/tf/keras/models/model_from_json) this must be a **json** file, but in the config model is referred to a **cfg** file. Where can I get the model json file?
> > 
> > 
> > Hi, did you already found the file? I am not really sure which json file that you meant, the first config json file is in the cfg folder while the trafficsigns json is in the data/classifier folder, you can refer 'issue about labels' and try to download data.zip if there is missing.
> > Goodluck! :)
> 
> yes, I got it working. thank you

how did you get it to work exactly. I have done everything in this thread and i still have the error.

**Comment by alevikpes** [comment]
hi! this was about some missing files, which I had. I do not know what was your error. If I remember correctly, I should have specified the paths to the yolo weights and to some config files. If you can provide some more details, I can try to help you.
