### ISSUE TITLE
real time detection

### ISSUE THREAD

**Issue by aiddddd** [ariaaan/traffic-signs-detector#18]
Hi, great works!

I would like to ask if you have any idea on how to make the detection works on webcam? I've stuck for days to make it real time detection. Hope that you can help me in solving this issue.

Regards, Aid.

**Comment by robhazes** [comment]
Yes, it is very easy. In the detector folder, open the detector.py file.
Search for the line 81 and 122: cap = cv2.VideoCapture(video_feed)
Just replace 'video_feed' with '0' 

0 is the number of the first cam in the system, usually your built in cam. You can add more cams and they will be assigned their own number. 

On my slow system I noticed a delay of approx. 4 seconds and a frame rate of 2 fps with the built in webcam. When I attached an external cam (I used an old smartphone and connected it by usb using Droidcam) the delay went down to 1 second. The frame rate stayed the same.  

Regards, Rob.

**Comment by aiddddd** [comment]
Wow! You save my day in just a minute! Thank you so much :)

**Comment by dida1** [comment]
Hi Rob, sorry i'm just a beginner, do you know what should i add to show the fps , the class and the accuracy of each detected object in my command prompt? 

Thanks!

**Comment by robhazes** [comment]
Sorry, I am a beginner myself and have no idea.

 

Hope you will find out.

 

Best regards,

 

Rob.

 

 

Fra: dida1 
Sendt: lørdag 6. juni 2020 16:42
Til: ariaaan/traffic-signs-detector <traffic-signs-detector@noreply.github.com>
Kopi: robhazes <robhazes@online.no>; Comment <comment@noreply.github.com>
Emne: Re: [ariaaan/traffic-signs-detector] real time detection (#18)

 

Hi Rob, sorry i'm just a beginner, do you know what should i add to show the fps , the class and the accuracy of each detected object in my command prompt?

Thanks!

**Comment by ariangilesgarcia** [comment]
Hi @dida1, I don't really understand what are you trying to do. If you explain yourself in more detail mabye I can give a a hint on how to accomplish that.

Have a good day!
