### ISSUE TITLE
How to run traffic signs detector 

### ISSUE THREAD

**Issue by aalzooke** [ariaaan/traffic-signs-detector#5]
I was looking on youtube your[ video ](https://www.youtube.com/watch?v=nf6rk56wYuI)
but I don't know how to run your code. 
Please explain how to do that

**Comment by ariaaan** [comment]
Hi @aalzooke , did you try following the README file? It's in spanish but you could probably follow it just fine. I'll translate it later anyways.

**Comment by aalzooke** [comment]
Thank you for your quick response, yes I did follow your readme, but I don't know which file is the **main file** 
![screenshot from 2018-05-21 15-00-16](https://user-images.githubusercontent.com/14840496/40324880-ea1b6596-5d07-11e8-8a7a-441750be653e.png)

**Comment by ariaaan** [comment]
You need to create a new python file with the following content:

```python
from detector.detector import create_detector_from_file

detector = create_detector_from_file('<config_path>')
detector.detect_video_feed('<video_path>', output='output.avi')
```

Then, replace `<config_path>` with the `.cfg` file, probably `./cfg/config.json` and replace `<video_path>` with the path to the video you want to test it against.

**Comment by aalzooke** [comment]
![screenshot from 2018-05-21 15-26-59](https://user-images.githubusercontent.com/14840496/40325933-89dc2bee-5d0b-11e8-97d5-001fb3dc267b.png)

When I try to run Python main.py, I got the following error as shown above. 
Thank you

**Comment by aalzooke** [comment]
Please let me know once you have time

**Comment by ariaaan** [comment]
The error is on [this](https://github.com/ariaaan/traffic-signs-detector/blob/master/detector/detector.py#L132) line, it's a print, so maybe just comment it?

**Comment by aalzooke** [comment]
![screenshot from 2018-05-25 12-40-19](https://user-images.githubusercontent.com/14840496/40556005-065cd01e-6019-11e8-8c12-0826a6067ca2.png)
I did that but still giving me an error [](url)

**Would you please record a video showing how to run it ?** 
It will help alot

**Comment by ariaaan** [comment]
Are you using `python3`?

**Comment by aalzooke** [comment]
Yes

**Comment by ariaaan** [comment]
I really don't know, it must be something on your end, I've tried it on several computers and have no problem running it.

**Comment by aalzooke** [comment]
Honestly, I have tried many times and still can't run it. It will be very helpful if you take 10 munites of your time and upload a video showing how to run the code. 
thank you

**Comment by jayeshchoudhary** [comment]
> Honestly, I have tried many times and still can't run it. It will be very helpful if you take 10 munites of your time and upload a video showing how to run the code.
> Thank you

yes I am also getting issue while running the program. can you please make a video of step by step how to run program

**Comment by jayeshchoudhary** [comment]
can you please make a video on how to run this project from scratch like machine with no libraries and python installed.

**Comment by jayeshchoudhary** [comment]
wget https://ariangg.s3-sa-east-1.amazonaws.com/data.zip -O data.zip 
link is not working

**Comment by ariangilesgarcia** [comment]
Ok, i've just added all the needed files to the repo, you should be able to just install the requirements and run `python example_image.py` and a `predictions.jpg` should appear on the root directory.
I haven't tried it yet, but it should work.

**Comment by jayeshchoudhary** [comment]
I am trying to run this project on windows. I have all the requirements downloaded but getting some error in make init command 
![image](https://user-images.githubusercontent.com/41536903/66275231-6d8a3780-e83b-11e9-8446-04bce2211a96.png)
can you please help me

**Comment by ariangilesgarcia** [comment]
Don't run make init, just install the requirements and run the examples to see if it works.
And BTW, I don't use windows, so I can't help you with any issues that may cause.

**Comment by jayeshchoudhary** [comment]
sample video link is not working
