### ISSUE TITLE
can you share the other link for download

### ISSUE THREAD

**Issue by gucasbrg** [ariaaan/traffic-signs-detector#7]
http://138.197.90.173:8080/data.zip
Connecting to 138.197.90.173:8080... failed: Connection timed out.
tks

**Comment by ariaaan** [comment]
Sorry for the delay, I'm having problems with the server the files were in. 
Here are the [YOLO files](https://drive.google.com/drive/folders/0B0g6FQ9sSGwzbkpuTEN3YmNhWmM?usp=sharing), and the [classifier files](https://drive.google.com/drive/folders/0B0g6FQ9sSGwzTW5MdTVZZzFjSjA?usp=sharing).

I'm gonna try to the get the server up and running again, but in the meanwhile, you can try with those files.
