### ISSUE TITLE
*.weights files for yolo 

### ISSUE THREAD

**Issue by iulianmaciuca** [ariaaan/traffic-signs-detector#8]
Hi, 

      Can you share the *.weights for yolo ? They are missing and the specified archive can not be downloaded (timeout). Can you help me ? 

Thanks

**Comment by JYewman** [comment]
I'm having the same issue...

**Comment by iulianmaciuca** [comment]
I wasn't able to find it on the darknet site either. I don't know which version of yolo it is..

**Comment by ariaaan** [comment]
Sorry, I'm having problems with the server the files were in. [Here](https://drive.google.com/drive/folders/0B0g6FQ9sSGwzbkpuTEN3YmNhWmM?usp=sharing) is the weights file for the YOLO model.

**Comment by JYewman** [comment]
Thanks 👍

**Comment by robhazes** [comment]
Hi again, I am using this weights file and it works. But it detects both 50 kmh and 60 kmh as 100 % 60 kmh. So I think their might be something wrong or maybe it is not the latest version of your weights file?

Also, I wonder if the dataset you used to train the model is available for download somewhere?

Best regards, Rob.

**Comment by ariangilesgarcia** [comment]
Hi @robhazes 
It is the latest version of the weights file, but I didn't have enough training data for the `50-kmh` sign.
I "fixed" (🤦‍♂️it's clearly NOT a fix) that problem with a configuration field. You can check that out [here](https://github.com/ariaaan/traffic-signs-detector/blob/master/cfg/example.config.json#L16).

I have the dataset for the Keras classifier that I can [share](https://drive.google.com/file/d/0B0g6FQ9sSGwzTkVhYlRuaGFmUnM/view?usp=sharing) with you, but sadly I lost the dataset for the YOLO model. I have [some](https://drive.google.com/open?id=0B0g6FQ9sSGwzQlN3M3RPZDAzOUk) of the images, but I think I've lost the final dataset.

**Comment by robhazes** [comment]
Okay, that explains what I am experiencing, thanks. I have downloaded the files and will check if I can use them.

**Comment by robhazes** [comment]
The dataset is very useful. I already have a german dataset, but it lacks the speeds 40 90 110 130, The german set includes 70 and "end of 80" which are missing in your set. By merging these sets the dataset will become complete in respect to the speed limits :) 

Correction: 90 is missing in both sets, so if anyone has this class please let me know...

**Comment by ariangilesgarcia** [comment]
Nice! Please keep me updated with your work, and feel free to ping me if I can be of any help! 😄

**Comment by SpawN1337** [comment]
Hello @ariangilesgarcia i couldnt get the yolo weights i made a rquest to get the google drive saved model can you share it please
thank you
